import path from "node:path";
import type { MoniconPlugin, MoniconPluginFile } from "@monicon/core/plugins";

type MyPluginOptions = {
	outputPath?: string;
};

export const iconsGenPlugin: MoniconPlugin<MyPluginOptions> = (options) => () => {
	const { outputPath = ".monicon" } = options;

	return {
		name: "icon-file-plugin",

		// eslint-disable-next-line perfectionist/sort-objects -- Ignore
		afterWriteFiles: () => {
			console.info("[Monicon] Finished icon generation!");
		},

		generate: (ctx) => {
			const files: MoniconPluginFile[] = [];

			const entries = ctx.icons.map(
				(icon) =>
					`	"${icon.name}": ${JSON.stringify({
						height: icon.height,
						svgBody: icon.body,
						width: icon.width,
					})}`
			);

			const entriesString = entries.join(", \n\n");

			files.push({
				content: getIconFileContent({ entriesString }),
				path: path.join(outputPath, "icons.ts"),
			});

			return files;
		},
	};
};

const getIconFileContent = (options: { entriesString: string }) => {
	const { entriesString } = options;

	return `// This file is automatically generated by Monicon. Do not edit this file directly.
export const moniconLocalIcons = {
${entriesString}
};
`;
};
