import { defineEnum } from "@zayne-labs/toolkit-type-helpers";

export const icons = defineEnum(
	[
		"basil:caret-down-outline",
		"bi:chevron-double-right",
		"bi:chevron-right",
		"bi:chevron-up",
		"material-symbols:check-rounded",
		"bi:facebook",
		"bi:instagram",
		"bi:menu-button-fill",
		"bi:moon-stars-fill",
		"bi:pinterest",
		"bi:twitter",
		"ant-design:heart-filled",
		"bi:youtube",
		"bx:cart-alt",
		"bx:heart",
		"bx:search-alt-2",
		"bx:user",
		"fa:facebook",
		"fa:google",
		"fa6-brands:google",
		"fa6-solid:chevron-down",
		"fa6-solid:sun",
		"material-symbols:mail-rounded",
		"material-symbols:mark-email-unread-rounded",
		"material-symbols:error-rounded",
		"ant-design:star-filled",
		"lucide:chevron-right",
		"mdi:cart",
		"ant-design:heart-outlined",
		"mdi:cart-outline",
		"mdi:email",
		"mdi:map-marker",
		"mdi:minus-circle",
		"mdi:phone",
		"mdi:plus-circle",
		"radix-icons:paper-plane",
		"ri:close-fill",
		"ri:menu-3-fill",
		"tabler:trash-filled",
		"typcn:arrow-back",
	],
	{ inferredUnionVariant: "values" }
);
