import path from "node:path";
import type { MoniconPlugin, MoniconPluginFile } from "@monicon/core/plugins";

type MyPluginOptions = {
	outputPath?: string;
};

export const iconFilePlugin: MoniconPlugin<MyPluginOptions> = (options) => (payload) => {
	const { outputPath = ".monicon" } = options;

	return {
		name: "icon-file-plugin",

		// eslint-disable-next-line perfectionist/sort-objects -- Ignore
		afterWriteFiles: () => {
			console.info("[Monicon] Finished icon generation!");
		},
		generate: () => {
			const files: MoniconPluginFile[] = [];

			// Generate icons.ts file with all icons
			const iconEntries = payload.icons.map((icon) => {
				const iconData = {
					height: icon.height || 16,
					svgBody: icon.body,
					width: icon.width || 16,
				};
				return `  "${icon.name}": ${JSON.stringify(iconData)}`;
			});

			const iconsContent = `// This file is automatically generated by Monicon. Do not edit this file directly.
export const moniconLocalIcons = {
${iconEntries.join(",\n")}
};
`;

			files.push({
				content: iconsContent,
				path: path.join(outputPath, "icons.ts"),
			});

			// 			// Generate types.d.ts file
			// 			const iconNames = payload.icons.map((icon) => `	| "${icon.name}"`).join("\n");

			// 			const typesContent = `// This file is automatically generated by Monicon. Do not edit this file directly.

			// declare global {
			//   export type MoniconIconName =
			// ${iconNames};

			//   export type MoniconProps = {
			//     /**
			//      * The name of the icon to render.
			//      *
			//      * @example "mdi:home"
			//      *
			//      * For TypeScript users, you must check below for more information.
			//      *
			//      * @link https://monicon-docs.vercel.app/troubleshooting/typescript
			//      */
			//     name: MoniconIconName;
			//     /**
			//      * The size of the icon.
			//      *
			//      * @default collection's view box size
			//      */
			//     size?: number;
			//     /**
			//      * The color of the icon.
			//      *
			//      * @default "currentColor"
			//      */
			//     color?: string;
			//   };
			// }`;

			// 			files.push({
			// 				content: typesContent,
			// 				path: path.join(".monicon", "types.d.ts"),
			// 			});

			return files;
		},
	};
};
